source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'FLTestPod_Example', :exclusive => true do
  pod "FLTestPod", :path => "../"
end

target 'FLTestPod_Tests', :exclusive => true do
  pod "FLTestPod", :path => "../"

  
end
